const data ={
    product:[
        {
            _id:'1',
            name:'The alchemist',
            category: 'books',
            image:'/images/p1.jpg',
            price: 100,
            brand: 'A',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Rich dad poor dad',
            category: 'books',
            image:'/images/p2.jpg',
            price: 80,
            brand: 'A',
            rating: 3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'The lean startup',
            category: 'books',
            image:'/images/p3.jpg',
            price: 105,
            brand: 'A',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Eleven minutes',
            category: 'books',
            image:'/images/p4.jpg',
            price: 140,
            brand: 'A',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'You can win',
            category: 'books',
            image:'/images/p5.jpg',
            price: 95,
            brand: 'A',
            rating: 2.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'The chamber of secrets',
            category: 'books',
            image:'/images/p6.jpg',
            price: 125,
            brand: 'A',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'7',
            name:'My experiments with truth',
            category: 'books',
            image:'/images/p7.jpg',
            price: 195,
            brand: 'A',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'8',
            name:'The jungle book',
            category: 'books',
            image:'/images/p8.jpg',
            price: 65,
            brand: 'A',
            rating: 3,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data;